$(document).ready(function(){
    $("#first").click(function(){
        $("#firstp").slideToggle('slow');
    });
    $("#second").click(function(){
        $("#secondp").slideToggle('slow');
    });
    $("#third").click(function(){
        $("#thirdp").slideToggle('slow');
    });
});